#!/bin/bash -eu

# This script disables XMonad's automatic re-builds in favor of manual
# rebuilds. Run `update` to rebuild.

SRC_DIR=$HOME/xmonad
XMONAD_DIR="$HOME/.xmonad"

ln -sf "$XMONAD_DIR/xmonad" "$1"

