#!/bin/bash -eu

# This script re-builds XMonad and places the resulting binary at
# ~/.xmonad/xmonad

EXE_NAME="xmonad"
INSTALL_DIR="$HOME/.xmonad/"

cabal install exe:"$EXE_NAME" \
    --enable-executable-stripping \
    --enable-optimization=2 \
    --installdir="$INSTALL_DIR" \
    --overwrite-policy=always

